# Generated by Django 6.1.2 on 2026-10-07 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='topic',
            constraint=models.UniqueConstraint(fields=('meeting', 'name'), name='unique_topic_per_meeting'),
        ),
    ]
